version: '3.8'

services:
  e2e-app:
    build:
      context: .
      dockerfile: Dockerfile.e2e
      target: runtime
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
      - CI=true
      - HEADLESS=true
    volumes:
      # Mount source code for development (hot reload)
      - ./projects:/app/projects
      - ./src:/app/src
      - ./features:/app/features
      - ./wdio.conf.ts:/app/wdio.conf.ts
    networks:
      - e2e-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  e2e-tests:
    build:
      context: .
      dockerfile: Dockerfile.e2e
      target: runtime
    depends_on:
      e2e-app:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - CI=true
      - HEADLESS=true
      - BASE_URL=http://e2e-app:4200
    command: >
      sh -c "
        echo 'Waiting for app to be ready...' &&
        sleep 10 &&
        echo 'Running E2E tests...' &&
        wdio run wdio.conf.ts
      "
    volumes:
      - ./features:/app/features
      - ./wdio.conf.ts:/app/wdio.conf.ts
      - ./allure-results:/app/allure-results
    networks:
      - e2e-network

networks:
  e2e-network:
    driver: bridge
