
// Auto-generated by scripts/generate-sentry-config.js during CI/build
// Do not edit directly. DSNs are public identifiers and safe to ship.
module.exports = {
  mainDsn: "https://foo@o123.ingest.sentry.io/1",
  rendererDsn: "https://bar@o123.ingest.sentry.io/2"
};
