name: Node Setup

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '24.5.0'
      cache-dependency-path:
        required: false
        type: string
        default: 'package-lock.json'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.cache-dependency-path }}

      - name: Install dependencies
        run: npm ci
